-- 코드를 입력하세요
SELECT (CASE
    WHEN PRICE < 10000 THEN 0
    ELSE SUBSTR(PRICE, 1, 1) * 10000
END) AS PRICE_GROUP, COUNT(PRODUCT_CODE) AS PRODUCTS
FROM PRODUCT
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP