-- 코드를 작성해주세요
SELECT HE.EMP_NO, HE.EMP_NAME, HG.GRADE, (CASE
    WHEN GRADE = 'S' THEN HE.SAL * 0.2
    WHEN GRADE = 'A' THEN HE.SAL * 0.15
    WHEN GRADE = 'B' THEN HE.SAL * 0.1
    WHEN GRADE = 'C' THEN HE.SAL * 0
END) AS BONUS
FROM HR_EMPLOYEES AS HE
JOIN (
    SELECT EMP_NO, (CASE
        WHEN (SUM(SCORE) / COUNT(SCORE)) >= 96 THEN 'S'
        WHEN (SUM(SCORE) / COUNT(SCORE)) >= 90 THEN 'A'
        WHEN (SUM(SCORE) / COUNT(SCORE)) >= 80 THEN 'B'
        ELSE 'C'
    END) AS GRADE
    FROM HR_GRADE
    GROUP BY EMP_NO
) AS HG
ON HE.EMP_NO = HG.EMP_NO
ORDER BY EMP_NO