-- 코드를 작성해주세요
SELECT HG.SCORE, HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM HR_EMPLOYEES AS HE
JOIN (
    SELECT SUM(SCORE) AS SCORE, EMP_NO
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
    ORDER BY SUM(SCORE) DESC
    LIMIT 1
) AS HG
ON HE.EMP_NO = HG.EMP_NO