-- 코드를 작성해주세요
SELECT FI1.ID, FNI.FISH_NAME, FI1.LENGTH
FROM FISH_INFO FI1
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS FI2
ON FI1.FISH_TYPE = FI2.FISH_TYPE AND FI1.LENGTH = FI2.max_length
JOIN FISH_NAME_INFO AS FNI
ON FI1.FISH_TYPE = FNI.FISH_TYPE
ORDER BY FI1.ID