-- 코드를 작성해주세요
SELECT ED2.YEAR,
    ED2.MAX_SIZE - ED1.SIZE_OF_COLONY AS YEAR_DEV,
    ED1.ID
FROM ECOLI_DATA AS ED1
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS ED2
ON YEAR(ED1.DIFFERENTIATION_DATE) = ED2.YEAR
ORDER BY YEAR, YEAR_DEV